settings:
  resource_types:
    machine:
      id: 0
      name: 'Maszyna'
      icon: 'cogs'
    location:
      id: 1
      name: 'Lokalizacja'
      icon: 'map-o'
    external:
      id: 2
      name: 'Zewnętrzny'
      icon: 'truck'